// SPDX-License-Identifier: MIT
// Loads the f64-patched Yoga reference build generated by
// `pnpm build:reference` (scripts/build-reference.mjs) into .reference/.

// @ts-ignore -- generated locally by scripts/build-reference.mjs
import wrapAssembly from "../../../.reference/yoga-f64/wrapAssembly.ts";
// @ts-ignore -- generated locally by the Yoga Emscripten build
import loadYoga from "../../../.reference/yoga-f64/yoga-wasm-base64-esm.js";

export async function loadReferenceYoga() {
  return wrapAssembly(await loadYoga());
}

const Yoga = await loadReferenceYoga();
export default Yoga;
